services:
  gameservice:
    build: 
      context: .
      dockerfile: GameService/Dockerfile  
    ports:
      - "5000:80"  
    depends_on:
      - postgres

  postgres:
    image: postgres:latest
    container_name: postgres-game
    environment:
      POSTGRES_USER: MainPalbmaUser
      POSTGRES_PASSWORD: palbma
      POSTGRES_DB: GameServiceDb
    ports:
      - "5436:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
   

















        
